# Code Generated by Sidekick is for learning and experimentation purposes only.
import json
import base64

def decode_and_validate_semgrep_output(encoded_output_file):
    try:
        with open(encoded_output_file, 'r') as file:
            encoded_output = file.read()
        decoded_output = base64.b64decode(encoded_output).decode('utf-8')
        data = json.loads(decoded_output)
    except (json.JSONDecodeError, base64.binascii.Error) as e:
        return f"Invalid encoded JSON format: {e}"

    valid_results = []
    for result in data.get('results', []):
        file_path = result.get('path')
        line_number = result.get('start', {}).get('line')
        rule_id = result.get('check_id')

        # Example validation criteria
        if file_path and isinstance(line_number, int) and rule_id:
            valid_results.append(result)
        else:
            print(f"Invalid result: {result}")

    return valid_results

# Example usage
encoded_output_file = 'semgrep_output_encoded.txt'
valid_results = decode_and_validate_semgrep_output(encoded_output_file)
print(f"Valid results: {valid_results}")
