name: Semgrep Scan

on: [push, pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep
        run: |
          # Run Semgrep with custom rules and disable metrics
          semgrep_output=$(semgrep --config p/default --config custom-rules.yml --json --metrics=off)
            
          
          # Check if Semgrep ran successfully
          if [ $? -ne 0 ]; then
            echo "Semgrep encountered an error."
            exit 1
          fi

          # Print Semgrep output
          echo "$semgrep_output"


      - name: Encode Semgrep Output
        run: |
          echo "$semgrep_output" | base64 > semgrep_output_encoded.txt

      - name: Commit and Push Encoded Output
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add semgrep_output_encoded.txt
          git commit -m 'Add encoded Semgrep output'
          git push




