name: Semgrep Scan

on: [push, pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep --config custom-rules.yml --json  "--metrics=off" > semgrep_output.json

      - name: Encode Semgrep Output
        run: |
          base64 semgrep_output.json > semgrep_output_encoded.txt

      - name: Commit and Push Encoded Output
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add semgrep_output_encoded.txt
          git commit -m 'Add encoded Semgrep output'
          git push



